# Generated by Django 6.0.6 on 2026-07-14 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_path', models.CharField(blank=True, max_length=1024, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='storage.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_path', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.folder')),
            ],
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'full_path'], name='storage_fol_user_id_b2667d_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'folder'], name='storage_fol_user_id_70ca20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'full_path')},
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'full_path'], name='storage_fil_user_id_2c96d5_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'folder'], name='storage_fil_user_id_4e0aba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('user', 'full_path')},
        ),
    ]
