# Generated by Django 6.0.6 on 2026-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='full_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
