[pytest]
DJANGO_SETTINGS_MODULE = config.settings
addopts = 
    --tb=short
    #--reuse-db
    --no-migrations
    --capture=no
    -v

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    django_db: Тесты использующие базу данных
    slow: Медленные тесты
    integration: Интеграционные тесты
    unit: Юнит-тесты
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore:.*django.db.models.fields.*:RuntimeWarning